services:
  - type: web
    name: live-chatapp-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SOCKET_URL
        value: https://live-chatapp-room.onrender.com
